---
title: "R Notebook"
output: html_notebook
---

# Load libraries
```{r}
library(Seurat)
library(SeuratData)
library(SeuratDisk)
```

```{r}
# Load object: may need to change path directory
obj <- readRDS("../Evolution of Cell Types/Analysis/Species_Objects/Final Objects/BCs/MarmosetFovea_BC_int_v1.rds")
DefaultAssay(obj) <- "RNA"

# First save as .h5Seurat
SaveH5Seurat(obj, filename = "Marmoset/BC/MarmosetFoveaBC.h5Seurat")
# Convert to .h5ad
Convert("Marmoset/BC/MarmosetFoveaBC.h5Seurat", dest = "h5ad")

# If you need to create the h5ad again, delete the old version first

```

# Adding metadata
```{r}
# Check metadata
head(obj@meta.data)
```



```{r}
# Relevant metadata columns 
# 1) sample ID (either orig.ident or orig.file, whichever is NOT possorted_genome_bam_XXXXX)
# 2) type. Metadata column is either called "type" and may be a number, or "annotated" which usually is a string
# 3) OT assignment. Run code below to generate this

OT_mammals <- readRDS("../Evolution of Cell Types/Analysis/Species_Objects/Final Objects/OTs/BC_types_mammals_v5.rds")
OT_nonmammals <- 
  
# Write metadata, including OT annotations
# If "type" is absent, use "annotated"
obj@meta.data$type <- obj$annotated
OT_names <- paste0(species,";", colnames(obj))
OT_names_in_m <- OT_names[OT_names %in% colnames(BC_m)]
OT_names_in_nm <- OT_names[OT_names %in% colnames(BC_nm)]
names_in_m <- colnames(object)[OT_names %in% colnames(BC_m)]
names_in_nm <- colnames(object)[OT_names %in% colnames(BC_nm)]


object@meta.data$Mammal_OT <- "absent"
object@meta.data$Nonmammal_OT <- "absent"
object@meta.data[names_in_m, "Mammal_OT"] <- as.vector(BC_m@meta.data[OT_names_in_m, "NOG"])
object@meta.data[names_in_nm, "Nonmammal_OT"] <- as.vector(BC_nm@meta.data[OT_names_in_nm, "NOG"])

fwrite(x = object@meta.data, row.names = TRUE, file = "../../Data Discovery Program/Marmoset/BC/MarmosetFovea_BC_metadata.csv")


# Write UMAP coordinates
fwrite(x = as.data.table(object@reductions$umap@cell.embeddings, keep.rownames = T), row.names = FALSE, file = "../../Data Discovery Program/Marmoset/BC/MarmosetFovea_BC_UMAP.csv")
```

